//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

// Espacio de nombres AccesoDatos
namespace AccesoDatos
{
    // Importación de espacio de nombres
    using System;
    using System.Collections.Generic;

    // Definición de la clase parcial Clientes
    public partial class Clientes
    {
        // Propiedad para el identificador del cliente
        public int id { get; set; }

        // Propiedad para la cédula del cliente
        public string cedula { get; set; }

        // Propiedad para el nombre del cliente
        public string nombre { get; set; }

        // Propiedad para la dirección del cliente
        public string direccion { get; set; }

        // Propiedad para el teléfono del cliente
        public string telefono { get; set; }

        // Propiedad para el identificador de la categoría del cliente, permite valores nulos
        public Nullable<int> idCategoria { get; set; }

        // Propiedad de navegación a la categoría del cliente
        public virtual Categoria Categoria { get; set; }
    }
}

